Updated
kishan1988-hub/TF-AWS-VPC pull request #1
Opened 2022-07-22 17:12 UTC by kishan1988-hub

Created TF for VPC creation

2022-07-22 17:35 UTC, vladimirmukhin requested changes
Please do the following:
- Remove all tags - we will add them properly later
- run "terraform fmt" and commit changes
- separate `count` meta-argument from the rest of the arguments using a new line
- adjust your code style so there is only one new line between different top-level resources

2022-07-22 17:35 UTC, vladimirmukhin requested changes
Please do the following:

- Remove all tags - we will add them properly later
- run "terraform fmt" and commit changes
- separate count meta-argument from the rest of the arguments using a new line
- adjust your code style so there is only one new line between different top-level resources

2022-07-22 17:51 UTC, kishan1988-hub commented
- Removed comment tags as per request
- performed terraform fmt - to format the tf script

I am not clear on the other two changes - can you please clarify

2022-07-23 20:05 UTC, vladimirmukhin approved these changes

2022-07-31 14:32 UTC, merged