Resource name
kishan1988-hub/TF-AWS-VPC pull request #4
Opened 2022-07-30 18:01 UTC by kishan1988-hub

Updated with resource names and formatted code with terraform fmt command

2022-08-01 22:41 UTC, vladimirmukhin requested changes
Not all resources are tagged. 
Please properly name all resources that support tagging.

Also, please add env_code variable to the name.
More info about nev_code in this video tutorial:
https://youtu.be/s5e9pQXqq-U

2022-08-02 06:41 UTC, kishan1988-hub commented
Requested changes have been made, please review

2022-08-03 01:49 UTC, vladimirmukhin requested changes

2022-08-03 01:49 UTC, vladimirmukhin commented on main.tf
> +    Name = "private-${var.env_code}"
```suggestion
    Name = var.env_code
```

2022-08-03 01:49 UTC, vladimirmukhin commented on main.tf
> +    Name = "${var.env_code}"
```suggestion
    Name = var.env_code
```

2022-08-03 01:49 UTC, vladimirmukhin commented on main.tf
> +    Name = " ${var.env_code}-public"
```suggestion
    Name = "${var.env_code}-public"
```

2022-08-03 01:49 UTC, vladimirmukhin commented on variable.tf
> +}
```suggestion
variable "public_cidr" {}
```

2022-08-03 01:49 UTC, vladimirmukhin commented on variable.tf
> +}
```suggestion
variable "private_cidr" {}
```

2022-08-03 01:49 UTC, vladimirmukhin commented on main.tf
>    route {
```suggestion
  vpc_id = aws_vpc.main.id
  
  route {
```

2022-08-03 02:06 UTC, vladimirmukhin approved these changes

2022-08-03 02:07 UTC, merged